# Site settings
title: Atlanta Gay | Atlanta Chat Line
description: Gay chat line in Atlanta, free trial chat line. 
keywords: Gay Chat Line, Atlanta Gay, Chatline
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
